---
- name: Ensure config dir
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ domain_exporter_config_dir }}"
    - "{{ domain_exporter_config_dir }}/sources"

- name: Include docker-related tasks
  include_tasks: run_in_docker.yml
  when: domain_exporter_run_in_docker

- name: Include standalone tasks
  include_tasks: run_standalone.yml
  when: not domain_exporter_run_in_docker
