---
- name: Get domain exporter
  become: yes
  become_user: root
  get_url:
    url: "https://github.com/caarlos0/domain_exporter/releases/download/v{{ domain_exporter_version }}/domain_exporter_{{ domain_exporter_arch }}.tar.gz"
    dest: "{{ domain_exporter_config_dir }}/sources/domain_exporter-{{ domain_exporter_version }}.{{ domain_exporter_arch }}.tar.gz"
    mode: 0644
    owner: root
    group: root

- name: Unzip domain exporter
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: "{{ domain_exporter_config_dir }}/sources/domain_exporter-{{ domain_exporter_version }}.{{ domain_exporter_arch }}.tar.gz"
    dest: "{{ domain_exporter_config_dir }}/sources/"
    creates: "{{ domain_exporter_config_dir }}/sources/domain_exporter"

- name: Copy exporter to PATH
  become: yes
  become_user: root
  copy:
    remote_src: yes
    src: "{{ domain_exporter_config_dir }}/sources/domain_exporter"
    dest: /usr/local/bin/domain_exporter
    mode: 0755
    owner: root
    group: root
  notify:
    - Restart domain exporter

- name: Create domain exporter user
  user:
    name: "{{ domain_exporter_user }}"
    comment: "domain exporter user"
    shell: /usr/sbin/nologin

- name: Exporters | domain exporter | Ensure domain exporter systemd unit
  become: yes
  become_user: root
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/domain-exporter.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_unitfile
  notify:
    - Restart domain exporter

- name: Exporters | domain exporter | Enable systemd service
  become: yes
  become_user: root
  systemd:
    name: "domain-exporter.service"
    enabled: yes
    daemon_reload: yes
    state: started
  when:
    - systemd_unitfile.changed
